### ISSUE TITLE
Subscriber supplier benefit: listing as recommended supplier.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/open_digital_cooperative#1]
AP: Talk to Aaron and Tim about articulating / honouring the supplier benefits. [ Finn ]

**Comment by finnlewis** [comment]
We did this, it was a good discussion.

Upshot: https://localgovdrupal.org/suppliers/our-suppliers only lists current subscribing suppliers.

**Comment by markconroy** [comment]
Have suppliers that were removed from this page been notified? It would be good to let them know so they can get paid up and have themselves put back on the page.

**Comment by finnlewis** [comment]
Good call Mark!

@TJHDCR @aaronhirtenstein was there any communication to suppliers?
